name: weather-build-C

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y autoremove
        sudo apt -y install libcurl4-openssl-dev
    - name: Create build with CMake
      run: |
        sh ./build.sh
    - name : Test Run 'weather' App
      run: |
        cd bin/
        ./weather -v
