name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y autoremove
        sudo apt -y install libcurl4-openssl-dev
    - name: Get Build Environment
      run: |
        export CURRBD=$(pwd)
        ls -la
        printf "Current build directory: %s\n" "$CURRBD"
    - name: Create Build with CMake
      run: |
        printf "Current build directory: %s\n" "$CURRBD"
        cd $CURRBD
        $CURRBD/build.sh
    - name: Build with 'make'
      run: |
        cd $CURRBD/build
        make
    - name : Test Run 'weather' App
      run: |
        pwd
        ls -l
        $CURRBD/build/weather
