name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y autoremove
        sudo apt -y install libcurl4-openssl-dev
    - name: Create Build with CMake
      run: sh ./build.sh
    - name: Build with 'make'
      run: cd ./build ; make
    - name : Test Run 'weather' App
      run: |
        pwd
        ls -l
        weather
